---
apiVersion: v1
kind: Service
metadata:
  name: helloworld-app
  namespace: app
spec:
  selector:
    app: helloworld-app
  type: NodePort
  ports:
  - protocol: TCP
    port: 80          # Port the service exposes
    targetPort: 5000  # Port on the pods to forward traffic to